### ISSUE TITLE
2nd subcon door doesnt always revert

### ISSUE THREAD

**Issue by leftypem** [TheIncredibleHouk/MushroomMayhem#37]
Sometimes when you go into the 2nd subcon door, it doesnt revert back to the main map after the prerequisite time, leaving you to go back therough the door manually and missing the intended opportunity to go to the lower part of the level.

**Comment by dahrkdaiz** [comment]
Was this done in the latest download that includes Floaty Waters?

**Comment by leftypem** [comment]
It was.
